# Generated by Django 4.0.3 on 2022-04-05 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar/avatar.png', upload_to='avatar')),
                ('about_user', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('LICENCE3', 'LICENCE 3'), ('MASTER2', 'MASTER 2')], max_length=50)),
                ('field', models.CharField(choices=[('SECURITY', 'SECURITY'), ('NETWORKS', 'NETWORKS'), ('IA', 'IA'), ('WEB DEVELOPMENT', 'WEB DEVELOPMENT'), ('SOFTWARE', 'SOFTWARE'), ('OTHER', 'OTHER')], max_length=50)),
                ('title', models.CharField(max_length=200, null=True)),
                ('abstract', models.TextField(null=True)),
                ('image', models.ImageField(default='guard_pages/default.jpg', upload_to='guard_pages')),
                ('file', models.FileField(upload_to='docs/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('download_nb', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Books', to='biblio.person')),
            ],
        ),
    ]
